name: E2E Tests

on:
  push:
    branches:
      - main
      - v2

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PORT: 3000
      NODE_ENV: test
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/ci-setup

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore pnpm store and node_modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.STORE_PATH }}
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set up supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Copy env file and start Supabase in background
        run: |
          cp .env.local.example .env.local
          supabase start --exclude realtime,imgproxy,studio,edge-runtime &
          echo "Supabase starting in background..."

      - name: Install Playwright in background
        run: |
          pnpm exec playwright install chromium &
          wait

      - name: Wait for Supabase to be ready
        run: |
          timeout=180
          counter=0
          echo "Waiting for Supabase to be ready..."
          until curl -s http://localhost:54321/rest/v1/ > /dev/null; do
            if [ $counter -eq $timeout ]; then
              echo "Timeout waiting for Supabase"
              exit 1
            fi
            counter=$((counter+1))
            echo "Waiting... ($counter/$timeout)"
            sleep 1
          done
          echo "Supabase is ready!"

      - name: Wait for Inbucket to be ready
        run: |
          timeout=180
          counter=0
          echo "Waiting for Inbucket to be ready..."
          until curl -s http://localhost:54324 > /dev/null; do
            if [ $counter -eq $timeout ]; then
              echo "Timeout waiting for Inbucket"
              exit 1
            fi
            counter=$((counter+1))
            echo "Waiting... ($counter/$timeout)"
            sleep 1
          done
          echo "Inbucket is ready!"

      - name: Run e2e tests
        run: pnpm run test:e2e
        env:
          CI: true
          NODE_ENV: test

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-failure-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
